service:
  name: tenisliga-chat-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage,'dev'}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello

  chatkitAuth:
    handler: api/chatkitAuth.authenticate
    events:
      - http:
          path: api/authenticate
          method: post

  loadInitialData:
    handler: api/chatkitUsers.loadInitialData
    events:
      - http:
          path: api/loadInitialData
          method: post
          cors: true

  createUser:
    handler: api/chatkitUsers.createUser
    events:
      - http:
          path: api/createUser
          method: post
          cors: true

  updateUser:
    handler: api/chatkitUsers.updateUser
    events:
      - http:
          path: api/updateUser
          method: post
          cors: true

  deleteUser:
    handler: api/chatkitUsers.deleteUser
    events:
      - http:
          path: api/deleteUser
          method: post
          cors: true

  bulkCreateUsers:
    handler: api/chatkitUsers.bulkCreateUsers
    events:
      - http:
          path: api/bulkCreateUsers
          method: post
          cors: true

  createLeagueRooms:
    handler: api/chatkitRooms.createLeagueRooms
    events:
      - http:
          path: api/createLeagueRooms
          method: post
          cors: true

  deleteLeagueRooms:
    handler: api/chatkitRooms.deleteLeagueRooms
    events:
      - http:
          path: api/deleteLeagueRooms
          method: post
          cors: true